// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

export const metadata: Metadata = {
  title: "BDG Licitações e Assessoria | Excelência em Licitações Públicas",
  description: "Soluções estratégicas e completas para empresas que desejam participar de processos licitatórios com segurança, eficiência e competitividade. Consultoria especializada em licitações públicas.",
  keywords: [
    "licitações",
    "licitações públicas",
    "assessoria em licitações",
    "consultoria licitações",
    "BDG Licitações",
    "processos licitatórios",
    "compras governamentais",
    "editais",
    "propostas licitações",
    "Junqueirópolis",
    "São Paulo"
  ],
  authors: [{ name: "BDG Licitações e Assessoria" }],
  creator: "BDG Licitações e Assessoria",
  publisher: "BDG Licitações e Assessoria",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "pt_BR",
    url: "https://bdglicitacoes.com.br",
    title: "BDG Licitações e Assessoria | Excelência em Licitações Públicas",
    description: "Soluções estratégicas e completas para empresas que desejam participar de processos licitatórios com segurança, eficiência e competitividade.",
    siteName: "BDG Licitações e Assessoria",
    images: [
      {
        url: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=1200&h=630&fit=crop",
        width: 1200,
        height: 630,
        alt: "BDG Licitações e Assessoria",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "BDG Licitações e Assessoria | Excelência em Licitações Públicas",
    description: "Soluções estratégicas e completas para empresas que desejam participar de processos licitatórios.",
    images: ["https://images.unsplash.com/photo-1557804506-669a67965ba0?w=1200&h=630&fit=crop"],
  },
  alternates: {
    canonical: "https://bdglicitacoes.com.br",
  },
  verification: {
    google: "google-site-verification-code",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="scroll-smooth">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        
        {/* Schema.org JSON-LD para SEO */}
        <Script
          id="schema-org"
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "ProfessionalService",
              name: "BDG Licitações e Assessoria",
              description: "Empresa especializada em licitações públicas e assessoria empresarial",
              url: "https://bdglicitacoes.com.br",
              telephone: "+55-18-99815-4084",
              email: "guilherme.licitacoes@hotmail.com",
              address: {
                "@type": "PostalAddress",
                streetAddress: "Rua das Américas, 580",
                addressLocality: "Junqueirópolis",
                addressRegion: "SP",
                postalCode: "17890-202",
                addressCountry: "BR"
              },
              geo: {
                "@type": "GeoCoordinates",
                latitude: -21.5167,
                longitude: -51.4333
              },
              areaServed: {
                "@type": "State",
                name: "São Paulo"
              },
              priceRange: "$$",
              openingHoursSpecification: {
                "@type": "OpeningHoursSpecification",
                dayOfWeek: [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday"
                ],
                opens: "08:00",
                closes: "18:00"
              },
              sameAs: []
            })
          }}
        />
      </head>
      <body className="font-inter antialiased">
        {children}
      </body>
    </html>
  );
}
